In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('clouds.png')

# cv2.imshow('clouds',img)
# waitKey() waits for a key press to close the window and 0 specifies indefinite loop
# cv2.waitKey(0)
# Destroys all the windows created
# cv2.destroyAllwindows() 

### question 1: dimension of image array

In [8]:
img.shape

(600, 400, 3)

### assignment 1: Crop the image so it becomes square by chopping of the bottom part.

In [9]:
img_cropped = img[0:400,:,:]
# Display cropped image
# cv2.imshow("cropped", img_cropped)  
# cv2.waitKey(0)



48

### assignment 2: Discolor the image by reducing the intensity of the red value of every pixel by half.

In [ ]:
img_colored = img_cropped


### BGR
img_colored[:,:,2] //= 2
# cv2.imshow("img_colored", img_colored)  
# cv2.waitKey(0)


### Assignment 3: Discolor the image by doubling the intensity of the red value of every pixel. You may have to handle an overow problem.

In [5]:
img = cv2.imread('clouds.png')
print(img[0,0])

# casten want anders overflow en dan kan je niet meer clippen
img = img.astype("uint64")
print(img.dtype)
img[:,:,2] *= 2
img = np.clip(img,0,255)
img = img.astype("uint8")

cv2.imshow("img", img)  
cv2.waitKey(0)
print(img[0,0])

[119  57  55]
uint64
[119  57 110]


### Assignment 4: Make a regular grid of black dots on the image so that the dots are 10 pixels apart vertically and horizontally, like in the image below

In [9]:
### gebruik .copy ipv opnieuw in te lezen, gewoon gelijkstellen past ook originele foto aan
# geen np.copy want dat is shallow 
img = cv2.imread('clouds.png')

# -9 voor onderste rij, 
img[9:-9:10,9:-9:10,:] = (0,0,0)
cv2.imshow("img", img)  
cv2.waitKey(0)

48

### 3 Thresholding
Thresholding is a method to segment grayscale images. It can be used to find objects of interest in images.
Pixel intensity values are compared to a threshold value and classified according to whether they are higher
or lower than this value. Finding the correct threshold value is often not trivial.

### assignment 5 convert the image to grayscale

In [3]:
gray = img.copy()
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("gray", gray)  
cv2.waitKey(0)

48

### Assignment 6 Threshold the grayscale image at 50% of the maximum value for this datatype.

In [4]:
threshold_img = gray.copy()
# thresh1 is thresholdfoto, ret geeft gebruikte threshold weer 
ret,thresh1 = cv2.threshold(threshold_img,127,255,cv2.THRESH_BINARY)
cv2.imshow("thresh1", thresh1)  
cv2.waitKey(0)

48

### Assignment 7 Threshold the grayscale image at the ideal threshold determined by Otsu's method.

In [6]:
# Otsu's thresholding
threshold_img_otsu = gray.copy()
ret2,th2 = cv2.threshold(threshold_img_otsu,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
cv2.imshow("thresh2", th2)  
cv2.waitKey(0)

48

## Excercise 3

### Assignment 8 Adaptively threshold the grayscale version of painting2.png so you get a similar result to the one below, where the background is uniformly white and you can cut out the painting along black lines.

In [21]:
painting = cv2.imread("painting2.jpg")
painting_gray = cv2.cvtColor(painting, cv2.COLOR_BGR2GRAY)
# als blokgrootte kleiner is, fijner
# gaussian minder stippen
th3 = cv2.adaptiveThreshold(painting_gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,11,12)
cv2.imshow("thresh2", th3)  
cv2.waitKey(0)

48

## Exercise 4

### Assignment 9 Remove the white noise from whitenoise.png by Gaussian filtering.

In [22]:
whitenoise = cv2.imread("whitenoise.png")
blur = cv2.GaussianBlur(whitenoise,(5,5),0)
cv2.imshow("blur", blur)  
cv2.waitKey(0)

48

### Question 2 What is the effect on the sharpness of the image?
Answer: The picture is more blurry then the original. The sharpness decreases.

## Excercise 5

### Assignment 10 Test the Gaussian filter on saltandpeppernoise.png.

In [24]:
salt_and_peper = cv2.imread("saltandpeppernoise.png")
gaussian_salt = cv2.GaussianBlur(salt_and_peper,(5,5),0)
cv2.imshow("gaussian", gaussian_salt)  
cv2.waitKey(0)

48

### Assignment 11 Apply median filtering on the same image.

In [27]:
salt_and_peper_median = cv2.imread("saltandpeppernoise.png")
median_salt = cv2.medianBlur(salt_and_peper_median,5)
cv2.imshow("median", median_salt)  
cv2.waitKey(0)

48

### Question 3 Which result is preferable and why?
Answer: Median filtering is preferable. Gaussian filter is a linear type of filter which is based on Gaussian function. But the median filter is a non-linear type of filter. 

It preserves edge while removing noise. By taking the median of all the pixels under the kernel area and replacing the central element with this median value, edges are being preserved. This is highly effective against salt-and-pepper noise in an image.

## Exercise 6 

### Assignment 11 Implement unsharp masking to sharpen unsharp.png. Make sure you do not get overflow in your datatype! Your goal is to achieve something similar to the image below.

In [2]:
unsharp = cv2.imread("unsharp.png")

blurred = unsharp.copy()

blurred = cv2.GaussianBlur(blurred,(5,5),0)
blurred = blurred.astype("float32")
unsharp_float32 = unsharp.astype("float32")


difference = unsharp_float32 - blurred

print(difference)
# Here you have to also define the weightage for each image that is alpha and beta. In this example, I am setting 
# the alpha value to 0.3 and the beta value to 0.7. The constant y is 0. Add the following line of code to continue.


result = cv2.addWeighted(unsharp_float32,1,difference,10,0)
clipped = np.clip(result,0,255)
clipped_uint8 = clipped.astype("uint8")

cv2.imshow("unsharp", unsharp)  
cv2.waitKey(0)


cv2.imshow("endresult", clipped_uint8)  
cv2.waitKey(0)

[[[-1.  0.  0.]
  [-1.  1.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[-1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ...

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


48

## exercise 7

### Assignment 12 Write a program that blurs blots.png diagonally with the kernel below (mind the multiplication factor in front).

In [20]:
blots = cv2.imread("blots.png")

kernel = np.zeros((15,15))
identity = np.identity(7)
padded = np.pad(identity, [(0, 8), (0, 8)], mode='constant', constant_values=0)
kernel = np.add(kernel, padded)

kernel *= 1/7


# Applying the filter2D() function
filter2D = cv2.filter2D(src=blots, ddepth=-1, kernel=kernel)
cv2.imshow("filter2D", filter2D)  
cv2.waitKey(0)


# coordinaat is 8,8

0